spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/myMall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 3309
  session:
    store-type: redis
    timeout: -1
  servlet:
    multipart:
      max-file-size: 10485760

server:
  servlet:
    context-path: /mall
  session:
    timeout: -1
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


fancx:
  ssh:
    user: root
    password: Fanjingge123
    host: 39.107.106.124
    port: 22
    local_port_mysql: 3308
    local_port_Redis: 3309
    remote_host: 172.25.59.31
    remote_port_mysql: 3306
    remote_port_Redis: 6379
